### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tobiash** [Soreil/arw#2]
Hi,
I would be interested in forking this to refactor out the gtk viewer code and use it for a side project of mine. Would you be willing to put a License on your project?

**Comment by Soreil** [comment]
Sure thing, I'll put a license on it that gives you more or less full freedom. I hope you can find a use for the code!I can get to a computer again in a few hours to make the change.Op 7 sep. 2018 18:40 schreef tobiash <notifications@github.com>:Hi,
I would be interested in forking this to refactor out the gtk viewer code and use it for a side project of mine. Would you be willing to put a License on your project?

**Comment by Soreil** [comment]
I added an MIT license to the project, I hope this works for you.

**Comment by tobiash** [comment]
Thanks!
